### ISSUE TITLE
Error handling node http

### ISSUE THREAD

**Issue by klossteles** [dojot/flowbroker#99]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
After receiving a message from a device, flowborker try to handle node http but gets `TypeError: Cannot read property 'shift' of null.`
Important: Message data is saved on device.
Logs: 
``` bash
auth_1                        | 172.26.0.20 - - [17/Jan/2019:17:14:29 +0000] "GET /admin/tenants HTTP/1.1" 200 22 "-" "axios/0.18.0"
flowbroker_1                  | Constructor
flowbroker_1                  | [ingestor] Failed to acquire existing tenancy contexts - consumerDevice is not defined
data-broker_1                 | <17:14:29 17/01/2019> -- |sub-mng| -- DEBUG: Received a topic GET request.
data-broker_1                 | <17:14:29 17/01/2019> -- |sub-mng| -- DEBUG: Topic for service admin and subject device-data.
data-broker_1                 | <17:14:29 17/01/2019> -- |topicManager| -- DEBUG: Retrieving/creating new topic...
data-broker_1                 | <17:14:29 17/01/2019> -- |topicManager| -- DEBUG: Subject: device-data
data-broker_1                 | <17:14:29 17/01/2019> -- |sub-mng| -- DEBUG: Received a topic GET request.
data-broker_1                 | <17:14:29 17/01/2019> -- |sub-mng| -- DEBUG: Topic for service admin and subject dojot.device-manager.device.
data-broker_1                 | <17:14:29 17/01/2019> -- |topicManager| -- DEBUG: Retrieving/creating new topic...
data-broker_1                 | <17:14:29 17/01/2019> -- |topicManager| -- DEBUG: Subject: dojot.device-manager.device
data-broker_1                 | <17:14:29 17/01/2019> -- |topicManager| -- DEBUG: ... topic was properly created/retrievied.
data-broker_1                 | <17:14:29 17/01/2019> -- |topicManager| -- DEBUG: Handling all pending requests...
data-broker_1                 | <17:14:29 17/01/2019> -- || -- DEBUG: subject: device-data
data-broker_1                 | <17:14:29 17/01/2019> -- |topicManager| -- DEBUG: ... all pending requests were handled.
data-broker_1                 | <17:14:29 17/01/2019> -- |topicManager| -- DEBUG: ... topic was properly created/retrievied.
data-broker_1                 | <17:14:29 17/01/2019> -- |topicManager| -- DEBUG: Handling all pending requests...
data-broker_1                 | <17:14:29 17/01/2019> -- || -- DEBUG: subject: dojot.device-manager.device
data-broker_1                 | <17:14:29 17/01/2019> -- |topicManager| -- DEBUG: ... all pending requests were handled.
data-broker_1                 | <17:14:29 17/01/2019> -- || -- DEBUG: Creating topics with 1 partition(s)
data-broker_1                 | <17:14:29 17/01/2019> -- || -- DEBUG: and 1 replication factor...
data-broker_1                 | <17:14:29 17/01/2019> -- || -- DEBUG: ... topics creation was requested.
data-broker_1                 | <17:14:29 17/01/2019> -- || -- DEBUG: Creating topics with 1 partition(s)
data-broker_1                 | <17:14:29 17/01/2019> -- || -- DEBUG: and 1 replication factor...
data-broker_1                 | <17:14:29 17/01/2019> -- || -- DEBUG: ... topics creation was requested.
data-broker_1                 | ::ffff:172.26.0.20 - GET /topic/device-data HTTP/1.1 200 48 - 2.484 ms
data-broker_1                 | ::ffff:172.26.0.20 - GET /topic/dojot.device-manager.device HTTP/1.1 200 48 - 1.944 ms
kafka_1                       | [2019-01-17 17:14:29,408] WARN [Admin Manager on Broker 0]: Error processing create topic request for topic 929f05ed-03a9-48f4-bc0a-e7424e4ec18a with arguments org.apache.kafka.common.requests.CreateTopicsRequest$TopicDetails@2a4e64cb (kafka.server.AdminManager)
kafka_1                       | org.apache.kafka.common.errors.TopicExistsException: Topic "929f05ed-03a9-48f4-bc0a-e7424e4ec18a" already exists.
flowbroker_1                  | [kafka] Producer ready
rabbitmq_1                    | 2019-01-17 17:14:29.409 [info] <0.972.0> connection <0.972.0> (172.26.0.20:47720 -> 172.26.0.9:5672): user 'guest' authenticated and granted access to vhost '/'
kafka_1                       | [2019-01-17 17:14:29,411] WARN [Admin Manager on Broker 0]: Error processing create topic request for topic f0a99dac-ffd4-4fda-8c17-8106ab7ed7a2 with arguments org.apache.kafka.common.requests.CreateTopicsRequest$TopicDetails@1e1840db (kafka.server.AdminManager)
kafka_1                       | org.apache.kafka.common.errors.TopicExistsException: Topic "f0a99dac-ffd4-4fda-8c17-8106ab7ed7a2" already exists.
flowbroker_1                  | [kafka] Producer ready
flowbroker_1                  | [kafka] Producer ready
flowbroker_1                  | [kafka] Producer ready
flowbroker_1                  | [kafka] Created consumer (iotagent-377)[device-data : f0a99dac-ffd4-4fda-8c17-8106ab7ed7a2]
flowbroker_1                  | [kafka] Created consumer (iotagent-377)[dojot.device-manager.device : 929f05ed-03a9-48f4-bc0a-e7424e4ec18a]
flowbroker_1                  | [amqp] consumer ready ... 
kafka_1                       | [2019-01-17 17:14:29,432] INFO [GroupCoordinator 0]: Preparing to restabilize group iotagent-377 with old generation 1 (kafka.coordinator.GroupCoordinator)
flowbroker_1                  | [executor] will handle node http
flowbroker_1                  | debug: Executing http node...
flowbroker_1                  | debug: HTTP request about to be sent: Url {
flowbroker_1                  |   protocol: 'http:',
flowbroker_1                  |   slashes: true,
flowbroker_1                  |   auth: null,
flowbroker_1                  |   host: '192.168.100.113',
flowbroker_1                  |   port: null,
flowbroker_1                  |   hostname: '192.168.100.113',
flowbroker_1                  |   hash: null,
flowbroker_1                  |   search: null,
flowbroker_1                  |   query: null,
flowbroker_1                  |   pathname: '/guia/dojot/contrel',
flowbroker_1                  |   path: '/guia/dojot/contrel',
flowbroker_1                  |   href: 'http://192.168.100.113/guia/dojot/contrel',
flowbroker_1                  |   method: 'POST',
flowbroker_1                  |   headers: {} }
flowbroker_1                  | /opt/flowbroker/orchestrator/node_modules/@dojot/flow-node/DataHandlerBase.js:72
flowbroker_1                  |         let key = source.shift();
flowbroker_1                  |                          ^
flowbroker_1                  | 
flowbroker_1                  | TypeError: Cannot read property 'shift' of null
flowbroker_1                  |     at DataHandler._set (/opt/flowbroker/orchestrator/node_modules/@dojot/flow-node/DataHandlerBase.js:72:26)
flowbroker_1                  |     at RedirectableRequest.req.request (/opt/flowbroker/orchestrator/src/nodes/http/index.js:195:22)
flowbroker_1                  |     at emitOne (events.js:116:13)
flowbroker_1                  |     at RedirectableRequest.emit (events.js:211:7)
flowbroker_1                  |     at RedirectableRequest._processResponse (/opt/flowbroker/orchestrator/node_modules/follow-redirects/index.js:258:10)
flowbroker_1                  |     at ClientRequest.RedirectableRequest._onNativeResponse (/opt/flowbroker/orchestrator/node_modules/follow-redirects/index.js:39:10)
flowbroker_1                  |     at Object.onceWrapper (events.js:315:30)
flowbroker_1                  |     at emitOne (events.js:116:13)
flowbroker_1                  |     at ClientRequest.emit (events.js:211:7)
flowbroker_1                  |     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
flowbroker_1                  |     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
flowbroker_1                  |     at Socket.socketOnData (_http_client.js:440:20)
flowbroker_1                  |     at emitOne (events.js:116:13)
flowbroker_1                  |     at Socket.emit (events.js:211:7)
flowbroker_1                  |     at addChunk (_stream_readable.js:263:12)
flowbroker_1                  |     at readableAddChunk (_stream_readable.js:250:11)
mongodb_1                     | 2019-01-17T17:14:29.489+0000 I NETWORK  [conn16] end connection 172.26.0.20:42934 (5 connections now open)
rabbitmq_1                    | 2019-01-17 17:14:29.489 [warning] <0.972.0> closing AMQP connection <0.972.0> (172.26.0.20:47720 -> 172.26.0.9:5672, vhost: '/', user: 'guest'):
rabbitmq_1                    | client unexpectedly closed TCP connection
rabbitmq_1                    | 2019-01-17 17:14:29.490 [warning] <0.960.0> closing AMQP connection <0.960.0> (172.26.0.20:47714 -> 172.26.0.9:5672, vhost: '/', user: 'guest'):
rabbitmq_1                    | client unexpectedly closed TCP connection
rabbitmq_1                    | 2019-01-17 17:14:29.490 [warning] <0.954.0> closing AMQP connection <0.954.0> (172.26.0.20:47710 -> 172.26.0.9:5672, vhost: '/', user: 'guest'):
rabbitmq_1                    | client unexpectedly closed TCP connection
dojot_flowbroker_1 exited with code 1
iotagent-mqtt_1               | <17:14:34 17/01/2019> -- INFO: client up
iotagent-mqtt_1               | <17:14:34 17/01/2019> -- DEBUG: Authorizing MQTT client 62e20140-abbd-4a38-b381-d14d457a4583 to publish to /admin/e83931/attrs
iotagent-mqtt_1               | <17:14:34 17/01/2019> -- DEBUG: will attempt to use topic as tenant source /admin/e83931,admin,e83931
iotagent-mqtt_1               | <17:14:34 17/01/2019> -- DEBUG: Expected topic is /admin/e83931/attrs
iotagent-mqtt_1               | <17:14:34 17/01/2019> -- DEBUG: Device published on topic /admin/e83931/attrs
iotagent-mqtt_1               | <17:14:34 17/01/2019> -- DEBUG: Authorized client 62e20140-abbd-4a38-b381-d14d457a4583 to publish to topic /admin/e83931/attrs
iotagent-mqtt_1               | <17:14:34 17/01/2019> -- DEBUG: ignoring internal message
iotagent-mqtt_1               | <17:14:34 17/01/2019> -- DEBUG: Published
iotagent-mqtt_1               | <17:14:34 17/01/2019> -- DEBUG: will attempt to use topic as tenant source /admin/e83931,admin,e83931
iotagent-mqtt_1               | <17:14:34 17/01/2019> -- DEBUG: Trying to publish someting. Current producer topics are { 'device-data': { admin: 'f0a99dac-ffd4-4fda-8c17-8106ab7ed7a2' } }
device-manager_1              | [17/01/19 - 17:14:35] |StatusMonitor| DEBUG:  Got kafka event [f0a99dac-ffd4-4fda-8c17-8106ab7ed7a2] ConsumerRecord(topic='f0a99dac-ffd4-4fda-8c17-8106ab7ed7a2', partition=0, offset=3, timestamp=1547745274510, timestamp_type=0, key=None, value=b'{"metadata":{"deviceid":"e83931","tenant":"admin","timestamp":1547745274510},"attrs":{"active_energy":"0.000000","active_power":"0.123230","apparent_energy":"0.000000","apparent_power":"2.667603","current":"0.011902","device_id":"e83931","luminosity_analog":"14.000000","luminosity_digital":"229376.000000","power_factor":"0.046143","power_frequency":"60.039307","reactive_energy":"0.000000","reactive_power":"0.000000","temperature":"30.460388","timestamp":"1547745274","voltage":"223.791077"}}', checksum=1367937770, serialized_key_size=-1, serialized_value_size=495)
device-manager_1              | [17/01/19 - 17:14:35] |StatusMonitor| INFO:  will set admin:e83931 online for 5s
device-manager_1              | [17/01/19 - 17:14:35] |StatusMonitor| DEBUG:  Got kafka event [f0a99dac-ffd4-4fda-8c17-8106ab7ed7a2] ConsumerRecord(topic='f0a99dac-ffd4-4fda-8c17-8106ab7ed7a2', partition=0, offset=4, timestamp=1547745275528, timestamp_type=0, key=None, value=b'{"metadata": {"deviceid": "e83931", "tenant": "admin", "status": "online", "reason": "statusUpdate"}}', checksum=3152650525, serialized_key_size=-1, serialized_value_size=101)
device-manager_1              | [17/01/19 - 17:14:37] |StatusMonitor| DEBUG:  scan st:admin:*:0:exp 0 [b'st:admin:e83931:0:exp']
device-manager_1              | [17/01/19 - 17:14:37] |StatusMonitor| DEBUG:  gc devices ['st:admin:e83931:0:exp']
device-manager_1              | [17/01/19 - 17:14:37] |StatusMonitor| DEBUG:  will check st:admin:e83931:0:exp 1547745280.5282142
device-manager_1              | [17/01/19 - 17:14:39] |StatusMonitor| DEBUG:  scan st:admin:*:0:exp 0 [b'st:admin:e83931:0:exp']
device-manager_1              | [17/01/19 - 17:14:39] |StatusMonitor| DEBUG:  gc devices ['st:admin:e83931:0:exp']
device-manager_1              | [17/01/19 - 17:14:39] |StatusMonitor| DEBUG:  will check st:admin:e83931:0:exp 1547745280.5282142
device-manager_1              | [17/01/19 - 17:14:41] |StatusMonitor| DEBUG:  scan st:admin:*:0:exp 0 [b'st:admin:e83931:0:exp']
device-manager_1              | [17/01/19 - 17:14:41] |StatusMonitor| DEBUG:  gc devices ['st:admin:e83931:0:exp']
device-manager_1              | [17/01/19 - 17:14:41] |StatusMonitor| DEBUG:  will check st:admin:e83931:0:exp 1547745280.5282142
device-manager_1              | [17/01/19 - 17:14:41] |StatusMonitor| DEBUG:  device st:admin:e83931:0:exp offline
device-manager_1              | [17/01/19 - 17:14:41] |StatusMonitor| DEBUG:  Got kafka event [f0a99dac-ffd4-4fda-8c17-8106ab7ed7a2] ConsumerRecord(topic='f0a99dac-ffd4-4fda-8c17-8106ab7ed7a2', partition=0, offset=5, timestamp=1547745281337, timestamp_type=0, key=None, value=b'{"metadata": {"deviceid": "e83931", "tenant": "admin", "status": "offline", "reason": "statusUpdate"}}', checksum=2295718547, serialized_key_size=-1, serialized_value_size=102)
kafka_1                       | [2019-01-17 17:14:44,394] INFO [GroupCoordinator 0]: Stabilized group iotagent-377 generation 2 (kafka.coordinator.GroupCoordinator)
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Json used to create current template: 
```json
{
  "label": "device_template",
  "attrs": [
        {
          "label": "temperature",
          "type": "dynamic",
          "value_type": "float"
        },
        {
          "label": "current",
          "type": "dynamic",
          "value_type": "float"
        },
        {
          "label": "apparent_power",
          "type": "dynamic",
          "value_type": "float"
        },
        {
          "label": "power_factor",
          "type": "dynamic",
          "value_type": "float"
        },
        {
          "label": "voltage",
          "type": "dynamic",
          "value_type": "float"
        },
        {
          "label": "active_power",
          "type": "dynamic",
          "value_type": "float"},
        {
          "label": "power_frequency",
          "type": "dynamic",
          "value_type": "float"},
        {
          "label": "reactive_power",
          "type": "dynamic",
          "value_type": "float"},
        {
          "label": "timestamp",
          "type": "dynamic",
          "value_type": "float"}
      ]
}
```

Json used to create one device: 
```json
{
  "templates": [
    "1"
  ],
  "label": "device"
}
```

Json used to create data_flow:
```json
{
  "id" : "faac9884-ad6f-4ff2-b6fa-4022ac39e472",
  "enabled": true,
  "name": "server_flow",
  "service" : "admin",
  "servicePath" : "/",
  "flow": [
            {
              "id":"8b63f794.763678",
              "label":"Flow 1",
              "type":"tab"
            },
            {
              "device_template":{
                "id":1
              },
              "device_template_id":1,
              "device_template_label":"device_template",
              "id":"9daa90ce.41da1",
              "name":"device_template_server",
              "type":"device template in",
              "wires":[["fdc745a6.6a5c58"]],
              "x":166.5,
              "y":118,
              "z":"8b63f794.763678"
            },
            {
              "field":"payload",
              "fieldType":"msg",
              "format":"handlebars",
              "id":"fdc745a6.6a5c58",
              "name":"template_server",
              "output":"str",
              "syntax":"mustache",
              "template":"{\"device_id\":\"{{payload.device_id}}\",\"Corrente\":{{payload.current}},\"Temperatura\":{{payload.temperature}},\"Lux\":{{payload.luminosity_analog}},\"Potência Aparente\":{{payload.apparent_power}},\"Fator de Potência\":{{payload.power_factor}},\"Tensão\":{{payload.voltage}},\"power_frequency\":{{payload.power_frequency}},\"Potência Reativa\":{{payload.reactive_power}},\"Potência Ativa\":{{payload.active_power}},\"timestamp\":{{payload.timestamp}}}",
              "type":"template",
              "wires":[["8891e7ee.c2dea8"]],
              "x":381.5,
              "y":176,
              "z":"8b63f794.763678"
            },
            {
              "body":"payload",
              "method":"POST",
              "id":"8891e7ee.c2dea8",
              "name":"server_connection",
              "ret":"txt",
              "type":"http",
              "url":"http://192.168.100.113/guia/dojot/contrel",
              "wires":[],
              "x":559.5,
              "y":242,
              "z":"8b63f794.763678"
            }
          ]
}
```

Send a message with mosquitto as it is on the dojot docs and it occurs the error.

* **What is the expected behavior?**
Dojot send the message throw http node.

* **Please tell us about your environment:**
  
  - Version: 0.3.x or master
  - Environment: docker-compose
  - Operating system: Linux Mint 19.1 Cinnamon

**Comment by raulnegreiros** [comment]
Hi @klossteles,

thanks for reporting this issue.

It seems that the http's configuration "response" is missing in your configuration, but the current behavior is not correct. We'll discuss to find out a better way to signalize it and avoid this kind of situation and put some validations.

A tip to try to avoid this kind of situation is verify if there is any field in the node configuration in red, these fields are mandatory and needed to be filled.

Best regards

**Comment by raulnegreiros** [comment]
Some points about your template node's configuration:
- luminosity_analog
- device_id

These attributes are not present on your data model, it can result in an empty value during the template engine evaluation. It's just a warning.

About the http's configuration:
the body parameters need be a json with a specific format, you can refer to [this example](https://dojotdocs.readthedocs.io/en/latest/flow.html#using-http-node) to check out how to fill it.

**Comment by rascaraficci** [comment]
This issue will be closed due to inactivity
